export type NodeType = 
  | 'askAI' 
  | 'extractData' 
  // ... other existing types ...
  | 'sendEmail'
  | 'readEmails'
  | 'createDraft'
  | 'sendSlackMessage'
  | 'slackNotification'
  | 'createSlackChannel'
  | 'sendSMS'
  | 'bulkSMS'
  | 'receiveSMS'
  | 'sendDiscordMessage'
  | 'createDiscordChannel'
  | 'manageRoles'
  | 'createPR'
  | 'createBranch'
  | 'commitChanges'